# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: "compatip"
before:
  hooks:
    - go mod download

builds:
  -
    id: "compatip"
    main: ./cmd/compatip/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
nfpms:
  -
    id: "compatip"

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://jordi.io/
    maintainer: Jordi Martin <jordimartin@gmail.com>
    description: Compatip it's a simple tool to ensure compatibility between microservices.
    license: MIT
    formats:
      - deb
      - rpm
#brews:
#  -
#    name: "compatip"
#    github:
#      owner: jmartin82
#      name: homebrew-compatip
#    commit_author:
#      name: Jordi Martin
#      email: jordimartin@gmail.com
#    folder: Formula
#    homepage: "https://jordi.io/"
#    description: "Compatip it's a simple tool to ensure compatibility between microservices."

archives:
  -
    replacements:
        darwin: Darwin
        linux: Linux
        windows: Windows
        386: i386
        amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - typo
      - rollback
      - wip

env_files:
  github_token: .github