language: go
go:
  - 1.12.x

env:
  - GO111MODULE=on

install: true

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic `go list ./... | grep -v 'test\|generated'`

after_success:
  - bash <(curl -s https://codecov.io/bash)
